# PostgreSQL. Ensure the pg gem is installed:
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: aronemilsson
  password:
  host: localhost

development:
  <<: *default
  database: music_portfolio_development

test:
  <<: *default
  database: music_portfolio_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
